format = """
$aws\
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$golang\
$helm\
$nodejs\
$python\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$memory_usage\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
[aws.region_aliases]
eu-central-1 = "fr-euc1"
eu-west-1 = "ir-euw1"
us-east-1 = "va-use1"

[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💀 "
full_symbol = "🔋 "

[[battery.display]]
style = "bold red"
threshold = 15

[character]
error_symbol = "[✗](bold red) "
success_symbol = "[➜](bold green) "

[container]
format = "[$symbol \\[$name\\]]($style) "

[git_branch]
symbol = "🌱 "
truncation_length = 8
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
cherry_pick = "[🍒 PICKING](bold red)"
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[kubernetes]
disabled = false
format = '|[⛵ $context \($namespace\)](dimmed green) '
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[memory_usage]
disabled = false
format = "$symbol [${ram_pct}]($style) "
style = "bold dimmed green"
symbol = "🐏"
threshold = 75

[line_break]
disabled = false

[nodejs]
format = "via [🧶 $version](bold green) "

[status]
disabled = true
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
style = "bg:blue"
symbol = "🔴"

[time]
disabled = true
format = '🕙 [ $time ]($style) '
time_format = "%T"
utc_time_offset = "+3"
